#!/usr/bin/env python3
"""Package oversized immutable build artifacts for a bounded Pages asset gateway.

No game logic, external fetch destinations, account bindings or credentials.
Only generated output is touched; ordinary requests remain static via _routes.
"""
import argparse
import gzip
import hashlib
import json
from pathlib import Path

LIMIT = 25 * 1024 * 1024
WORKER = r'''// Generated by pack_assets.py. Fixed public-artifact map; no game state.
const encoded = __MAP__;
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const entry = Object.hasOwn(encoded, url.pathname) ? encoded[url.pathname] : null;
    if (!entry) return env.ASSETS.fetch(request);
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", {status: 405, headers: {Allow: "GET, HEAD"}});
    }
    const etag = '"' + entry.sha256 + '"';
    const headers = new Headers({
      "Content-Type": entry.type,
      "Content-Encoding": "gzip",
      "Cache-Control": entry.immutable ? "public, max-age=31536000, immutable" : "public, max-age=0, must-revalidate",
      "ETag": etag,
      "Vary": "Accept-Encoding",
      "X-Content-Type-Options": "nosniff",
      "Access-Control-Allow-Origin": "*",
    });
    if (request.headers.get("If-None-Match") === etag) {
      return new Response(null, {status: 304, headers});
    }
    if (request.method === "HEAD") return new Response(null, {headers});
    // Fixed same-site asset path. Never forward cookies, authorization or Range.
    url.pathname = entry.path;
    url.search = "";
    const asset = await env.ASSETS.fetch(new Request(url, {headers: {"Accept-Encoding": "identity"}}));
    if (!asset.ok || (asset.headers.get("Content-Type") || "").includes("text/html")) {
      return new Response("Build asset unavailable", {status: 502, headers: {"Cache-Control": "no-store"}});
    }
    // Already-compressed bytes must not be compressed a second time by Workers.
    return new Response(asset.body, {headers, encodeBody: "manual"});
  }
};
'''

def package(root: Path, threshold: int = 20 * 1024 * 1024) -> dict:
    root = root.resolve()
    if not (root / 'index.html').is_file():
        raise ValueError('Not a web build: index.html missing')
    for name in ['_worker.js', '_routes.json', 'encoded-assets.json']:
        if (root / name).exists():
            raise ValueError('Refusing to overwrite existing ' + name)
    entries = {}
    pending = []
    for p in sorted(root.rglob('*')):
        if p.is_symlink():
            raise ValueError('Symlink not permitted in published build')
        if not p.is_file() or p.suffix in {'.gz', '.br'}:
            continue
        if p.stat().st_size <= threshold:
            continue
        if p.suffix not in {'.json', '.wasm'}:
            if p.stat().st_size > LIMIT:
                raise ValueError('Asset needs external storage: ' + str(p.relative_to(root)))
            continue
        raw = p.read_bytes()
        packed = gzip.compress(raw, compresslevel=9, mtime=0)
        if len(packed) > LIMIT:
            raise ValueError('Compressed asset still exceeds Pages limit: ' + p.name)
        if gzip.decompress(packed) != raw:
            raise ValueError('Compression round-trip failure')
        sha = hashlib.sha256(raw).hexdigest()
        rel = '/' + p.relative_to(root).as_posix()
        entry = {'path': '/.encoded/' + sha + '.gz', 'type': 'application/wasm' if p.suffix == '.wasm' else 'application/json', 'sha256': sha, 'decoded_bytes': len(raw), 'uploaded_bytes': len(packed), 'immutable': sha[:16] in p.stem or p.suffix == '.wasm'}
        entries[rel] = entry
        pending.append((p, packed, entry))
    if len(entries) > 90:
        raise ValueError('Encoded route count exceeds bounded limit')
    # Remove build-time compression siblings only when their original exists.
    for p in list(root.rglob('*')):
        if p.is_file() and p.suffix in {'.gz', '.br'} and p.with_suffix('').is_file():
            p.unlink()
    for p, packed, entry in pending:
        target = root / entry['path'].lstrip('/')
        target.parent.mkdir(exist_ok=True)
        target.write_bytes(packed)
        p.unlink()
    if entries:
        (root / '_worker.js').write_text(WORKER.replace('__MAP__', json.dumps(entries, separators=(',', ':'))), encoding='utf-8')
        (root / '_routes.json').write_text(json.dumps({'version': 1, 'include': list(entries), 'exclude': []}, indent=2) + '\n')
    (root / 'encoded-assets.json').write_text(json.dumps(entries, indent=2) + '\n')
    for p in root.rglob('*'):
        if p.is_file() and p.stat().st_size > LIMIT:
            raise ValueError('Unpackaged oversized asset: ' + str(p.relative_to(root)))
    print(json.dumps(entries, indent=2))
    return entries

if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('directory', type=Path)
    ap.add_argument('--threshold', type=int, default=20 * 1024 * 1024)
    args = ap.parse_args()
    if args.threshold < 1 or args.threshold > LIMIT:
        ap.error('threshold must be between 1 byte and 25 MiB')
    package(args.directory, args.threshold)
